% @Author: luoqi 
% @Date: 2021-01-25 09:36:37 
% @Last Modified by:   luoqi 

function ft_data_show(num, org, dst, T_LIMIT)

    t = 1:1:T_LIMIT;
    
    plot(t, org(num, :, 1), ...
         t, dst(num, :, 2), ...
         t, dst(num, :, 3), ...
         t, dst(num, :, 4));
    grid on;
    legend("Input P", ...
           "Feedback P", ...
           "Feedback V", ...
           "Feedback T");
end
